// mutations types
export const SET_TOKEN = 'SET_TOKEN'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_DB_USER = 'SET_DB_USER'
export const SET_ERROR_RESPONSE = 'SET_ERROR_RESPONSE'
export const SET_PASSWORD_ERROR_RESPONSE = 'SET_PASSWORD_ERROR_RESPONSE'
export const SET_AUTH_RESPONSE = 'SET_AUTH_RESPONSE'
export const SET_CLEAR_PASSWORD_ERROR_MESSAGE = 'SET_CLEAR_PASSWORD_ERROR_MESSAGE'
export const SET_CLEAR_USER = 'SET_CLEAR_USER'
export const SET_RESET_PASSWORD = 'SET_RESET_PASSWORD'
export const SET_CLEAR_AUTH_RES = 'SET_CLEAR_AUTH_RES'

// actions types
export const SIGNIN = 'signin'
export const SIGNUP = 'signup'
export const CREATE_ADMIN = 'createAdmin'
export const GET_CURRENT_USER = 'getCurrentUser'
export const UPDATE_PASSWORD = 'updatePassword'
export const UPDATE_USER_INFO = 'updateUserInfo'
export const FETCH_USER_BY_ID = 'fetchUserById'
export const RESET_PASSWORD = 'resetPassword'
export const CLEAR_PASSWORD_ERROR_MESSAGE = 'clearPasswordErrorMessage'
export const CLEAR_USER = 'clearUser'
export const CLEAR_AUTH_RES = 'clearAuthRes'
